"""Agregar modelo Solicitud

Revision ID: 16baad6da076
Revises: 5e5751f2c4c9
Create Date: 2025-06-03 10:47:34.104828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16baad6da076'
down_revision = '5e5751f2c4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('insumo', sa.String(length=100), nullable=False),
    sa.Column('equipo_estandar', sa.String(length=100), nullable=True),
    sa.Column('justificacion', sa.Text(), nullable=False),
    sa.Column('jefatura', sa.String(length=100), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitud')
    # ### end Alembic commands ###
