"""Add imagen_insumo to Solicitud

Revision ID: 38aa08ab9991
Revises: 9224b59e28da
Create Date: 2025-06-12 12:57:36.124747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38aa08ab9991'
down_revision = '9224b59e28da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_insumo', sa.String(length=255), nullable=True))
        batch_op.drop_column('imagen_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_url', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('imagen_insumo')

    # ### end Alembic commands ###
