"""Add imagen_url to Solicitud

Revision ID: 9224b59e28da
Revises: d03ca962c6bb
Create Date: 2025-06-12 12:33:59.059910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9224b59e28da'
down_revision = 'd03ca962c6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('imagen_insumo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_insumo', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('imagen_url')

    # ### end Alembic commands ###
