"""Añadir columna imagen_insumo

Revision ID: d03ca962c6bb
Revises: 16baad6da076
Create Date: 2025-06-12 12:19:25.530426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03ca962c6bb'
down_revision = '16baad6da076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_insumo', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud', schema=None) as batch_op:
        batch_op.drop_column('imagen_insumo')

    # ### end Alembic commands ###
